### ISSUE TITLE
Does not work in Chrome

### ISSUE THREAD

**Issue by mcsagittarius** [freqdec/peekaboo#1]
This seems promising, but when i load your examples in Chrome Version 58.0.3029.110 (64-bit) all images are loaded instantly. There is no fade-in, and if i debug it i can see that the callback is triggered for all elements initially.

This is true for both examples.

**Comment by freqdec** [comment]
Hi, Chrome 58.0.3029.81 changed the behavior of the IO API so a small update to the script is required. I'll drop it in this weekend. Thanks for the notification!

**Comment by freqdec** [comment]
Well, that took a while but I've updated the script to align to the updated IntersectionObserver spec. Thanks for bringing it to my attention...
